### ISSUE TITLE
[BUG-UI] - Darkmode doesnt work in tx log popup

### ISSUE THREAD

**Issue by m0ham3dx** [samczsun/ethereum-transaction-viewer-frontend#11]
# Components

TX Log modal 

# Description 

Dark mode on tx log modal doesn't work.

# Repro

[https://i.ibb.co/t8m9Xzd/dmfif2.gif](https://i.ibb.co/t8m9Xzd/dmfif2.gif)

**Comment by samczsun** [comment]
fixed
