### ISSUE TITLE
"Failed to fetch trace" for UNI pool deployments

### ISSUE THREAD

**Issue by engn33r** [samczsun/ethereum-transaction-viewer-frontend#12]
I am getting an error of "Failed to fetch trace: failed to generate trace" with these transactions on ETH mainnet:
0xcc060328dd98056aa86b7ea5ffa40f432c3d2df02e015c9f03489de623b06b4e
0xf7dd336859d1c00c6f8cb718c4674eb78e8f1723863031e5f5c92671b5ed1b59
0xf87d91f3d72a8e912c020c2e316151f3557b1217b44d4f6b6bec126448318530

All three transactions involve a Uniswap pair/pool deployment. The first two are Uni V2 and the last is Uni V3. Could this be related to handling of internal tx or CREATE2?

How to recreate:
1. Pick any pool from https://info.uniswap.org/pools#/ or https://v2.info.uniswap.org/pairs
2. Look up the pair/pool address in Etherscan
3. The deployment tx is found under the "Internal Txns" tab and these deployment txs cause the error

**Comment by samczsun** [comment]
coincidentally i noticed this too and just fixed it
