### ISSUE TITLE
Clicking `Expand View` No Longer Handled

### ISSUE THREAD

**Issue by Haruxe** [samczsun/ethereum-transaction-viewer-frontend#6]
Both ![image](https://user-images.githubusercontent.com/71164900/194904528-0597ddc8-05d3-409b-8dae-238049e9b754.png) and ![image](https://user-images.githubusercontent.com/71164900/194904593-7acf3e63-c75a-425f-a8e0-3c64f44f6001.png)
are unresponsive to user input, despite being `"clickable"` and having the required functions to handle them.

**Comment by samczsun** [comment]
oops, fixed
